#!/bin/bash
#
# build-aaa-linux.sh — compile VhsDecodeAutoAudioAlign from the vendored C#
# source so the Linux bundle ships a self-built AAA instead of the prebuilt
# Windows .exe + Binah.dll (which needs host Mono at runtime, the original
# "mono not found on Ubuntu" failure).
#
# Usage: scripts/build-aaa-linux.sh [--src-dir <path>] [--out-dir <path>]
#
#   --src-dir  vendored AAA source directory
#              (default: src/audio-align/vendor/vhs_decode_auto_audio_align-src)
#   --out-dir  where to place the built VhsDecodeAutoAudioAlign.exe + Binah.dll
#              (default: ./build-aaa)
#
# Requires: mono-devel (msbuild/xbuild) + unzip. Install on:
#   OracleLinux 8 (x86_64 CI): dnf install --enablerepo=epel mono-devel unzip
#   Ubuntu 24.04 (arm64 CI):   apt install --no-install-recommends mono-devel unzip
#
# The single NuGet dependency (Binah 2.0.4) is vendored at
# <src-dir>/nuget/Binah.2.0.4.nupkg and extracted manually to the packages/
# dir the .csproj HintPath expects — no `nuget` CLI and no network fetch.
# (nuget is not packaged in EPEL 8, so relying on it would break the OL8 job.)
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Simon Inns

set -euo pipefail

SRC_DIR="src/audio-align/vendor/vhs_decode_auto_audio_align-src"
OUT_DIR="build-aaa"
SEMVER="1.0.2"          # vendored AAA version (keep in sync with VENDOR_INFO.txt)
V_MAJOR="1"
V_MINOR="0"
V_PATCH="2"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --src-dir) SRC_DIR="$2"; shift 2 ;;
        --out-dir) OUT_DIR="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

die() { echo "build-aaa-linux.sh: $*" >&2; exit 1; }

command -v msbuild >/dev/null 2>&1 || command -v xbuild >/dev/null 2>&1 || die "msbuild/xbuild not found (install mono-devel)"
MSBUILD="$(command -v msbuild || command -v xbuild)"
MSBUILD_BASENAME="$(basename "$MSBUILD")"
command -v unzip >/dev/null 2>&1 || die "unzip not found (install unzip)"

[ -d "$SRC_DIR" ] || die "src dir not found: $SRC_DIR"
[ -f "$SRC_DIR/VhsDecodeAutoAudioAlign.sln" ] || die "not an AAA source dir (no .sln): $SRC_DIR"
[ -f "$SRC_DIR/nuget/Binah.2.0.4.nupkg" ] || die "vendored Binah nupkg missing: $SRC_DIR/nuget/Binah.2.0.4.nupkg"

echo "Building AAA $SEMVER from $SRC_DIR"
echo "  mono:    $(mono --version 2>/dev/null | head -n1 || echo 'mono not on PATH (msbuild may still work)')"
echo "  msbuild: $MSBUILD"

# Oracle Linux 8's Mono toolchain exposes xbuild 14.0, which does not support
# TargetFrameworkVersion v4.7.2 from the vendored project and fails with
# CSC CS0518 ("System.Object not defined or imported"). When xbuild is the
# active builder, down-target to v4.5 (compatible with the vendored Binah net45
# dependency) while preserving v4.7.2 on modern msbuild toolchains.
MSBUILD_FRAMEWORK_ARGS=()
if [ "$MSBUILD_BASENAME" = "xbuild" ]; then
    MSBUILD_FRAMEWORK_ARGS=(/p:TargetFrameworkVersion=v4.5)
fi

# Make OUT_DIR absolute relative to the caller's CWD before we cd into the
# scratch WORK_DIR below. Otherwise a relative --out-dir (the CI passes
# "build-aaa") would be created inside WORK_DIR and deleted by the EXIT trap,
# leaving the caller's expected output directory empty — the package script
# then fails with "built exe missing in build-aaa".
case "$OUT_DIR" in
    /*) ;;
    *) OUT_DIR="$PWD/$OUT_DIR" ;;
esac

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# Copy the source into a scratch dir so the build (which writes into ../build
# and ../packages relative to the project) does not dirty the vendor tree.
cp -a "$SRC_DIR/." "$WORK_DIR/"
cd "$WORK_DIR"

# Restore the Binah NuGet dep WITHOUT the nuget CLI: a .nupkg is just a zip,
# and the .csproj references it via HintPath ..\packages\Binah.2.0.4\lib\net45\Binah.dll.
# Extract the vendored nupkg to that exact path so msbuild/xbuild resolves the
# reference. (nuget is not packaged in EPEL 8, so this avoids a hard dep on it
# and never touches the network.)
mkdir -p packages/Binah.2.0.4/lib/net45
unzip -o -q "$WORK_DIR/nuget/Binah.2.0.4.nupkg" "lib/net45/Binah.dll" -d "$WORK_DIR/nuget-extract"
mv "$WORK_DIR/nuget-extract/lib/net45/Binah.dll" packages/Binah.2.0.4/lib/net45/Binah.dll
rm -rf "$WORK_DIR/nuget-extract"
[ -f packages/Binah.2.0.4/lib/net45/Binah.dll ] || die "Binah.dll extraction failed"

# Regenerate BuildInfo.cs with the tbc-tools build provenance. The upstream
# placeholder (all zeros) is overwritten so show-build-info reports real data.
COMMIT="${AAA_BUILD_COMMIT:-$(git -C "$(pwd)" rev-parse HEAD 2>/dev/null || echo unknown)}"
COMMIT_SHORT="${COMMIT:0:8}"
BUILD_JOB="${AAA_BUILD_JOB:-local}"
BUILD_TIME="$(date --iso-8601=seconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)"
cat > VhsDecodeAutoAudioAlign/BuildInfo.cs <<EOF
// Generated by scripts/build-aaa-linux.sh — do not edit by hand
static class BuildInfo
{
    public const string Commit = "$COMMIT";
    public const string CommitShort = "$COMMIT_SHORT";
    public const string BuildJob = "$BUILD_JOB";
    public const string BuildTime = "$BUILD_TIME";

    public const string VersionMajor = "$V_MAJOR";
    public const string VersionMinor = "$V_MINOR";
    public const string VersionPatch = "$V_PATCH";

    public const string VersionSemantic = "$SEMVER";
}
EOF

# Build only the main project (not the .sln) to avoid pulling in the NUnit /
# NSubstitute test NuGet deps that are intentionally not vendored.
"$MSBUILD" VhsDecodeAutoAudioAlign/VhsDecodeAutoAudioAlign.csproj \
    "${MSBUILD_FRAMEWORK_ARGS[@]}" \
    /p:Configuration=Release \
    /p:WarningLevel=0 \
    /nologo /verbosity:minimal

[ -f build/VhsDecodeAutoAudioAlign.exe ] || die "build did not produce build/VhsDecodeAutoAudioAlign.exe"
# Binah.dll is restored into packages/Binah.2.0.4/lib/net45/ and msbuild
# copies it next to the exe when HintPath resolves; verify either location.
BINAH_DLL=""
for candidate in \
    "build/Binah.dll" \
    "packages/Binah.2.0.4/lib/net45/Binah.dll"; do
    if [ -f "$candidate" ]; then
        BINAH_DLL="$candidate"
        break
    fi
done
[ -n "$BINAH_DLL" ] || die "Binah.dll not found after build"

# Stage the built artifacts into the requested out dir.
mkdir -p "$OUT_DIR"
cp -f build/VhsDecodeAutoAudioAlign.exe "$OUT_DIR/"
cp -f "$BINAH_DLL" "$OUT_DIR/Binah.dll"
# Copy the AppImage packaging assets (AppRun, desktop, icon) so the caller
# can package the self-contained AppImage without re-referencing the vendor.
if [ -d appimage ]; then
    mkdir -p "$OUT_DIR/appimage"
    cp -af appimage/. "$OUT_DIR/appimage/"
fi

# Smoke test: confirm the built exe is a valid .NET assembly. We use `file`
# (already installed in both Linux CI jobs) rather than running the exe under
# host mono, because OL8's Mono 6.8 omits the unversioned libmono-native.so
# that Mono's dllmap targets, so `mono show-build-info` crashes with
# DllNotFoundException: System.Native on the first DateTime.Now (the AAA Log
# prefixes timestamps) — an environmental host-mono issue, not a build
# problem. The real runtime + self-containment check (bundled Mono, no host
# Mono) is the AppImage smoke test in package-aaa-appimage.sh.
if ! file "$OUT_DIR/VhsDecodeAutoAudioAlign.exe" 2>/dev/null | grep -qi "net assembly"; then
    die "built VhsDecodeAutoAudioAlign.exe is not a valid .NET assembly (file check failed)"
fi

echo "Built AAA $SEMVER -> $OUT_DIR/VhsDecodeAutoAudioAlign.exe (+ Binah.dll + appimage/)"
